[package]
name = "recsys-scraper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = ""



[dependencies]
recsys-core = { workspace = true }
recsys-embed-local = { path = "../recsys-embed-local" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { version = "1", features = ["full"] }
rand = "0.9"
reqwest = { version = "0.12", features = ["json", "blocking"] }
quick-xml = "0.36"